# Generated by Django 3.1.7 on 2021-05-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20210519_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donations',
            options={'verbose_name_plural': 'Donations'},
        ),
    ]
