# Generated by Django 3.1.7 on 2021-05-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Email Contacts',
            },
        ),
    ]
