# Generated by Django 3.1.7 on 2021-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='adopted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='neutered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
