# Generated by Django 3.1.7 on 2021-05-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20210511_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='rescued',
            field=models.DateField(blank=True, null=True),
        ),
    ]
