# Generated by Django 3.1.7 on 2021-05-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20210511_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='status',
            field=models.TextField(default='adopted'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
