# Generated by Django 3.1.7 on 2021-05-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_auto_20210511_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='age',
            field=models.CharField(default='adult', max_length=254),
            preserve_default=False,
        ),
    ]
