# Generated by Django 3.1.7 on 2021-05-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0010_auto_20210511_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='microchipped',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='vaccinated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
