# Generated by Django 3.1.7 on 2021-05-11 15:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0011_auto_20210511_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='profile',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
