# Generated by Django 3.1.7 on 2021-05-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0012_auto_20210511_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='resident',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
