# Generated by Django 3.1.7 on 2021-05-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0013_cat_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='tagline',
            field=models.CharField(default='Super playful', help_text='One line character description...', max_length=254),
            preserve_default=False,
        ),
    ]
