# Generated by Django 3.1.7 on 2021-05-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0014_cat_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.CharField(blank=True, help_text='Physical Description', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='tagline',
            field=models.CharField(blank=True, help_text='One line character description...', max_length=254, null=True),
        ),
    ]
