# Generated by Django 3.1.7 on 2021-05-24 15:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0015_auto_20210512_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
