# Generated by Django 3.1.7 on 2021-05-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0017_auto_20210524_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
